baseURL = "https://reliqstudios.com"
title = "Reliq Studios"
languageCode = "en-us"
theme = "reliqtheme"

[pagination]
  pagerSize = 10

[params]
  dateform = "Jan 2, 2006"
  dateformShort = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  
  # Metadata
  description = "Reliq Studios | Handcrafted Web Solutions"
  keywords = "web development, design, digital agency, seo, search engine optimisation, web design, front end, design"
  images = [""]
  
  # Plausible Analytics
  plausibleDataDomain = "reliqstudios.com"
  plausibleScriptSource = "/stats/js/script.outbound-links.pageview-props.tagged-events.js"
  
  # Features
  enableThemeToggle = false
  enableSharingButtons = true
  enableReadingTime = true
  
  [params.author]
    name = "Reliq Studios Team"

[params.Logo]
  path = "/logo.svg"
  alt = "Reliq Studios Logo"
  logoHomeLink = "/"

[params.footer]
  trademark = 2025
  rss = false
  copyright = false
  author = false
  bottomText = ["Reliq Studios"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[languages]
  [languages.en]
    weight = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  [languages.en.params]
    subtitle = "Creative Digital Solutions"

[menu]
